# Generated by Django 6.0 on 2025-12-22 19:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file', models.FileField(upload_to='message_attachments/%Y/%m/%d/')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=100)),
                ('file_size', models.BigIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(choices=[('inbox', 'Inbox'), ('sent', 'Sent'), ('announcement', 'Announcement'), ('alert', 'Alert')], max_length=20)),
                ('subject', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('is_important', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('normal', 'Normal'), ('important', 'Important'), ('urgent', 'Urgent'), ('critical', 'Critical')], default='normal', max_length=20)),
                ('status', models.CharField(choices=[('delivered', 'Delivered'), ('pending', 'Pending'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('announcement_type', models.CharField(blank=True, choices=[('urgent', 'Urgent'), ('update', 'Update'), ('info', 'Information')], max_length=20, null=True)),
                ('attachments_count', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['-timestamp'],
            },
        ),
    ]
