# Generated by Django 6.0 on 2026-01-05 10:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communications', '0003_initial'),
        ('patients', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['message', 'uploaded_at'], name='communicati_message_f863c8_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['sender', 'timestamp'], name='messages_sender__557813_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['recipient', 'is_read', 'timestamp'], name='messages_recipie_522a5d_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['message_type', 'timestamp'], name='messages_message_e63855_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['patient', 'timestamp'], name='messages_patient_39a27e_idx'),
        ),
    ]
