# Generated by Django 6.0 on 2026-01-06 20:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Default Shift', max_length=100)),
                ('shift_type', models.CharField(choices=[('morning', 'Morning (8AM-4PM)'), ('evening', 'Evening (4PM-12AM)'), ('night', 'Night (12AM-8AM)'), ('on_call', 'On-Call'), ('split', 'Split Shift'), ('custom', 'Custom')], max_length=20)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['start_time'],
                'indexes': [models.Index(fields=['shift_type'], name='schedules_s_shift_t_d0f5ff_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScheduleEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('event_type', models.CharField(choices=[('shift', 'Regular Shift'), ('on_call', 'On-Call Duty'), ('meeting', 'Meeting'), ('training', 'Training'), ('vacation', 'Vacation'), ('sick_leave', 'Sick Leave'), ('conference', 'Conference')], default='shift', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('all_day', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='scheduled', max_length=20)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('color', models.CharField(default='#3B82F6', max_length=7)),
                ('department', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_events', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.patient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_events', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedules.shift')),
            ],
            options={
                'ordering': ['start_date', 'start_time'],
                'indexes': [models.Index(fields=['user', 'start_date'], name='schedules_s_user_id_524b49_idx'), models.Index(fields=['start_date', 'end_date'], name='schedules_s_start_d_f03442_idx'), models.Index(fields=['event_type', 'status'], name='schedules_s_event_t_59d387_idx'), models.Index(fields=['department', 'start_date'], name='schedules_s_departm_29a509_idx')],
            },
        ),
        migrations.CreateModel(
            name='TemplateDay',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('notes', models.TextField(blank=True)),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='schedules.shift')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='days', to='schedules.scheduletemplate')),
            ],
            options={
                'ordering': ['day_of_week'],
                'unique_together': {('template', 'day_of_week')},
            },
        ),
    ]
