# Generated by Django 6.0 on 2025-12-28 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_first_time_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('doctor', 'Doctor'), ('admin', 'Administrator'), ('superadmin', 'Super Administrator')], default='doctor', max_length=20),
        ),
    ]
