# Generated by Django 6.0 on 2025-12-22 19:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('size', models.BigIntegerField()),
                ('file_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('uploading', 'Uploading'), ('uploaded', 'Uploaded'), ('error', 'Error')], default='pending', max_length=20)),
                ('progress', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='patient_uploads/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='patients.patient')),
            ],
            options={
                'db_table': 'upload_files',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProcessingOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_anonymize', models.BooleanField(default=False)),
                ('ai_analysis', models.BooleanField(default=False)),
                ('auto_3d', models.BooleanField(default=False)),
                ('send_notifications', models.BooleanField(default=True)),
                ('archive', models.BooleanField(default=False)),
                ('upload', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='processing_options', to='uploads.uploadfile')),
            ],
        ),
    ]
