# Generated by Django 6.0 on 2025-12-24 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadfile',
            name='last_modified',
            field=models.BigIntegerField(default=0),
        ),
    ]
