# Generated by Django 6.0 on 2026-01-07 20:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_initial'),
        ('uploads', '0002_uploadfile_last_modified'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DICOMMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(blank=True, max_length=255)),
                ('patient_id', models.CharField(blank=True, max_length=64)),
                ('patient_birth_date', models.DateField(blank=True, null=True)),
                ('patient_sex', models.CharField(blank=True, max_length=10)),
                ('study_instance_uid', models.CharField(blank=True, max_length=64)),
                ('study_date', models.DateField(blank=True, null=True)),
                ('study_description', models.TextField(blank=True)),
                ('accession_number', models.CharField(blank=True, max_length=64)),
                ('series_instance_uid', models.CharField(blank=True, max_length=64)),
                ('series_number', models.IntegerField(blank=True, null=True)),
                ('series_description', models.TextField(blank=True)),
                ('modality', models.CharField(blank=True, max_length=20)),
                ('rows', models.IntegerField(blank=True, null=True)),
                ('columns', models.IntegerField(blank=True, null=True)),
                ('bits_allocated', models.IntegerField(blank=True, null=True)),
                ('pixel_spacing', models.CharField(blank=True, max_length=50)),
                ('slice_thickness', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('manufacturer', models.CharField(blank=True, max_length=100)),
                ('institution_name', models.CharField(blank=True, max_length=200)),
                ('is_anonymized', models.BooleanField(default=False)),
                ('anonymization_date', models.DateTimeField(blank=True, null=True)),
                ('raw_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'DICOM Metadata',
                'verbose_name_plural': 'DICOM Metadata',
                'db_table': 'dicom_metadata',
            },
        ),
        migrations.CreateModel(
            name='UploadAccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('viewed', 'Viewed'), ('downloaded', 'Downloaded'), ('shared', 'Shared'), ('modified', 'Modified'), ('deleted', 'Deleted')], max_length=20)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'upload_access_logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AlterModelOptions(
            name='uploadfile',
            options={'ordering': ['-created_at'], 'permissions': [('can_view_all_uploads', 'Can view all uploads'), ('can_process_uploads', 'Can process uploads'), ('can_export_uploads', 'Can export uploads')]},
        ),
        migrations.AddField(
            model_name='processingoptions',
            name='compression_level',
            field=models.CharField(choices=[('none', 'None'), ('lossless', 'Lossless'), ('lossy', 'Lossy')], default='lossless', max_length=20),
        ),
        migrations.AddField(
            model_name='processingoptions',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='processingoptions',
            name='output_format',
            field=models.CharField(choices=[('original', 'Original'), ('jpeg', 'JPEG'), ('png', 'PNG'), ('dicom', 'DICOM'), ('pdf', 'PDF')], default='original', max_length=20),
        ),
        migrations.AddField(
            model_name='processingoptions',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('emergency', 'Emergency')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='processingoptions',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='accessed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accessed_uploads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='category',
            field=models.CharField(choices=[('xray', 'X-Ray'), ('ct', 'CT Scan'), ('mri', 'MRI'), ('ultrasound', 'Ultrasound'), ('photo', 'Clinical Photo'), ('document', 'Document'), ('other', 'Other')], default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='consent_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='file_hash',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='last_accessed',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='patient_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='processing_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='uploadfile',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploads', to=settings.AUTH_USER_MODEL, verbose_name='Uploaded by'),
        ),
        migrations.AlterField(
            model_name='processingoptions',
            name='archive',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='processingoptions',
            name='auto_anonymize',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddIndex(
            model_name='uploadfile',
            index=models.Index(fields=['status', 'created_at'], name='upload_file_status_728160_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadfile',
            index=models.Index(fields=['patient', 'created_at'], name='upload_file_patient_aadd52_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadfile',
            index=models.Index(fields=['category'], name='upload_file_categor_4f0180_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadfile',
            index=models.Index(fields=['uploaded_by', 'created_at'], name='upload_file_uploade_84b6d2_idx'),
        ),
        migrations.AddField(
            model_name='dicommetadata',
            name='upload',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dicom_metadata', to='uploads.uploadfile'),
        ),
        migrations.AddField(
            model_name='uploadaccesslog',
            name='upload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_logs', to='uploads.uploadfile'),
        ),
        migrations.AddField(
            model_name='uploadaccesslog',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_access_logs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='uploadaccesslog',
            index=models.Index(fields=['upload', 'timestamp'], name='upload_acce_upload__ff9164_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadaccesslog',
            index=models.Index(fields=['user', 'timestamp'], name='upload_acce_user_id_0cd309_idx'),
        ),
    ]
